apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: final
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "5"
        autoscaling.knative.dev/target: "50"
        autoscaling.knative.dev/class: "kpa.autoscaling.knative.dev"
        autoscaling.knative.dev/metric: "rps"
        networking.knative.dev/ingress.class: "kourier.ingress.networking.knative.dev"
    spec:
      containers:
        - image: ealen/echo-server:latest
          ports:
            - containerPort: 80
          env:
            - name: EXAMPLE_ENV
              value: "value"
            
        - image: romanchechyotkin/meter_agent:latest
          name: meter-agent-sidecar 
          env:
            - name: POD_NAME
              value: final
            - name: METER_URL
              value: host.docker.internal:5461
            - name: TENANT
              value: romanchechyotkin@gmail.com

